// Generated by tools/generate_firebase_config.dart. Do not edit.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError('Firebase is not configured for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBub2QM8HA4AaxQkyjaTF2BEKlWQCHUPQ',
    appId: '1:1019259738242:web:307b5e38d9387433307c9b',
    messagingSenderId: '1019259738242',
    projectId: 'irrigasim-3c73d',
    authDomain: 'irrigasim-3c73d.firebaseapp.com',
    storageBucket: 'irrigasim-3c73d.firebasestorage.app',
    measurementId: 'G-THCWRRVTD3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClAReAZI9anFtnI7ev3zBKHa4prbDEl4s',
    appId: '1:1019259738242:android:12a7527340771203307c9b',
    messagingSenderId: '1019259738242',
    projectId: 'irrigasim-3c73d',
    authDomain: 'irrigasim-3c73d.firebaseapp.com',
    storageBucket: 'irrigasim-3c73d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBub2QM8HA4AaxQkyjaTF2BEKlWQCHUPQ',
    appId: '1:1019259738242:ios:5d8ae3848a6e9d50307c9b',
    messagingSenderId: '1019259738242',
    projectId: 'irrigasim-3c73d',
    authDomain: 'irrigasim-3c73d.firebaseapp.com',
    storageBucket: 'irrigasim-3c73d.firebasestorage.app',    androidClientId: 'YOUR_ANDROID_CLIENT_ID.apps.googleusercontent.com',
    iosClientId: '1019259738242-dh1uscq38ckqv1fd8ch7hbdsm931e84g.apps.googleusercontent.com',
    iosBundleId: 'com.example.irrigasim',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyDBub2QM8HA4AaxQkyjaTF2BEKlWQCHUPQ',
    appId: '1:1019259738242:web:307b5e38d9387433307c9b',
    messagingSenderId: '1019259738242',
    projectId: 'irrigasim-3c73d',
    authDomain: 'irrigasim-3c73d.firebaseapp.com',
    storageBucket: 'irrigasim-3c73d.firebasestorage.app',
    measurementId: 'G-THCWRRVTD3',
  );
}
