import 'dart:convert';
import 'dart:io';

void main(List<String> args) {
  final root = Directory.current;
  final source = File('${root.path}/firebase.json');
  final dryRun = args.contains('--dry-run');
  if (!source.existsSync()) {
    stderr.writeln('Erro: firebase.json nao encontrado em ${root.path}');
    exitCode = 1;
    return;
  }

  final config = jsonDecode(source.readAsStringSync()) as Map<String, dynamic>;
  _write(root, 'lib/firebase_options.dart', _dartOptions(config), dryRun);
  _write(
    root,
    'android/app/google-services.json',
    const JsonEncoder.withIndent('  ').convert(_googleServices(config)),
    dryRun,
  );
}

String _dartOptions(Map<String, dynamic> config) {
  final project = config['project'] as Map<String, dynamic>;
  final android = config['android'] as Map<String, dynamic>;
  final ios = config['ios'] as Map<String, dynamic>;
  final web = config['web'] as Map<String, dynamic>;

  String options(String name, Map<String, dynamic> app, {bool iosApp = false}) {
    final iosFields = iosApp
        ? """
    androidClientId: '${ios['androidClientId']}',
    iosClientId: '${ios['iosClientId']}',
    iosBundleId: '${ios['bundleId']}',"""
        : '';
    final measurement = app['measurementId'] == null
        ? ''
        : "\n    measurementId: '${app['measurementId']}',";
    return """  static const FirebaseOptions $name = FirebaseOptions(
    apiKey: '${app['apiKey']}',
    appId: '${app['appId']}',
    messagingSenderId: '${project['number']}',
    projectId: '${project['id']}',
    authDomain: '${project['authDomain']}',
    storageBucket: '${project['storageBucket']}',$measurement$iosFields
  );""";
  }

  return """// Generated by tools/generate_firebase_config.dart. Do not edit.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
        return ios;
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        return web;
      default:
        throw UnsupportedError('Firebase is not configured for this platform.');
    }
  }

${options('web', web)}

${options('android', android)}

${options('ios', ios, iosApp: true)}

${options('linux', web)}
}
""";
}

Map<String, dynamic> _googleServices(Map<String, dynamic> config) {
  final project = config['project'] as Map<String, dynamic>;
  final android = config['android'] as Map<String, dynamic>;
  return {
    'project_info': {
      'project_number': project['number'],
      'project_id': project['id'],
      'storage_bucket': project['storageBucket'],
    },
    'client': [
      {
        'client_info': {
          'mobilesdk_app_id': android['appId'],
          'android_client_info': {'package_name': android['package']},
        },
        'api_key': [
          {'current_key': android['apiKey']},
        ],
      },
    ],
    'configuration_version': '1',
  };
}

void _write(Directory root, String path, String content, bool dryRun) {
  if (dryRun) {
    stdout.writeln('[dry-run] Geraria: $path');
    return;
  }
  final file = File('${root.path}/$path');
  file.parent.createSync(recursive: true);
  file.writeAsStringSync(content);
  stdout.writeln('Gerado: $path');
}
